name: PURGE_CACHE
on:
  push:
    branches: [ PY-MR ]
    paths:
      - 'version'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Purge CDN cache
        run: curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon-Observer@PY-MR/version
