name: PY_MR_DEPLOY
on:
  push:
    branches: 
      - "PY-MR"
    paths:
      - "version.txt"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: PY-MR
      - name: Update DB
        run: |
          wget -nc -O - https://ygocdb.com/api/v0/cards.zip | gunzip - > cards.json
      - name: Deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "autobuild"
      - name: Purge CDN cache
        run: curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon-Observer@PY-MR/version.txt
      - name: Set Version
        run: |
          VER=$(head -n 1 version.txt)
          echo "TAG_NAME=$VER" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
