name: PURGE_CACHE
on:
  push:
    branches: [ PY-MR ]
    paths:
      - 'version'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Purge CDN cache
        run: curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon-Observer@PY-MR/version
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          version-file: "./version"