name: PURGE_CACHE
on:
  push:
    branches: [ PY-MR ]
    paths:
      - 'version'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: test
        required: true
jobs:
  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Purge CDN cache
        run: curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon-Observer@PY-MR/version
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          version-file: "./version.test"
  build:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Purge CDN cache
        run: curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon-Observer@PY-MR/version
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          version-file: "./version"