name: TEST
on:
  push:
    branches: [ PY-MR ]
    paths:
      - 'version.txt'
  workflow_dispatch:
    inputs:
      action:
        type: environment
        default: test
        required: true
jobs:
  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: PY-MR
      - name: Set Version
        run: |
          VER=$(head -n 1 version.txt)
          echo "TAG_NAME=$VER" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
